-- Created by: Arena.ai Agent Mode (AI) - RoadRealism MTA:SA resource
-- GENERATED by source/build.py from source/rr/*.py - edit the database, then rebuild

-- RoadRealism runtime settings.  Everything here can also be changed from the chat box:
--   /roadquality low|medium|high|ultra   /roadrain <0-1>   /roadwet <0-1>   /roadreload
--   /roaddebug <0|1|2|3>   /roadfx <0-4>   /roadrefl <0-2>   /roadscan   /roadtextures
SETTINGS = {
    wetDryRate = 0.028,
    wetRiseRate = 0.2,
    wetMin = 0,
    wetMax = 1,
    puddleFrom = 0.35,
    puddleFull = 0.9,
    rainWeather = 8,
    rainWeatherDamp = 7,
    rainOwnWeather = true,
    rainSound = true,
    rainVolume = 0.55,
    reflectStrength = 1,
    reflectAnglePow = 2.6,
    reflectBlur = 1.6,
    reflectStretch = 2.4,
    nightRetro = 1.35,
    nightSpecBoost = 1.25,
    exposure = 1,
    maxShaders = 48,
    scanInterval = 4000,
    scanPerStep = 90,
    applyPerStep = 40,
    lazyDistance = 0,
    debug = false,
    -- safety switches
    autoApplyPatterns = false,   -- apply pattern guesses to unknown textures (risky)
    autoApplyReview = false,     -- apply the ambiguous "review" tier on start
    fallbackTXD = true,          -- engineImportTXD fallback when a shader will not compile
    preserveWeatherOnStop = true,
    defaultQuality = "high",
}
